=== guillegol/tema03/dtd_curriculum.dtd
<!ELEMENT curriculum (datos_personales, datos_academicos, experiencia_laboral)>
<!ATTLIST curriculum lang CDATA #REQUIRED>
<!ELEMENT datos_personales (nombre, apellidos, direccion, telefono, dni, decripcion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT decripcion (#PCDATA)>
<!ELEMENT datos_academicos (primaria, eso, grado_medio, grado_superior)>
<!ELEMENT primaria (#PCDATA)>
<!ELEMENT eso (#PCDATA)>
<!ELEMENT grado_medio (#PCDATA)>
<!ELEMENT grado_superior (#PCDATA)>
<!ELEMENT experiencia_laboral (farmacia)>
<!ELEMENT farmacia (empresa, fecha_de_inicio, fecha_de_finalicacion, trabajo_realizado, horario, dias)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT fecha_de_inicio (#PCDATA)>
<!ELEMENT fecha_de_finalicacion (#PCDATA)>
<!ELEMENT trabajo_realizado (#PCDATA)>
<!ELEMENT horario (#PCDATA)>
<!ELEMENT dias (#PCDATA)>

=== guillegol/tema03/curriculum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "dtd_curriculum.dtd">
<curriculum lang="es">
    <curriculum>
        <datos_personales>
            <nombre> Guillermo </nombre>
            <apellidos>Santos Juanes Zafra </apellidos>
            <direccion>Calle pansa n1 </direccion>
            <telefono>634346419</telefono>
            <dni>53942170V </dni>
            <decripcion>Hola soy Guillermo,tengo 18 a√±os y ahora mismo estoy estudiando ASIX en Javea en IES la Mar </decripcion>
        </datos_personales>
        <datos_academicos>
            <primaria>Carmelitas Denia</primaria>
            <eso>Carmelitas Denia</eso>
            <grado_medio>Ausias March Valencia</grado_medio>
            <grado_superior>cursando IES la Mar Javea</grado_superior>
        </datos_academicos>
        <experiencia_laboral>
            <farmacia>
                <empresa>Ferreres</empresa>
                <fecha_de_inicio>1 de junio</fecha_de_inicio>
                <fecha_de_finalicacion>31 de agosto</fecha_de_finalicacion>
                <trabajo_realizado>colocacion y venta de medicamentos</trabajo_realizado>
                <horario>9-13/17-20</horario>
                <dias>lunes a sabado</dias>
            </farmacia>
        </experiencia_laboral>
    </curriculum>
</curriculum>
